### PR TITLE
Feature/prebootstrap2

### PR DESCRIPTION
**Pull request by marksantcroos**
This is required to get ExecWorkers going on Cray compute nodes.

### CODE REVIEW

**Comment by andre-merzky** [comment]
why not double quotes?  Because this is usually specified in a json?  I don't like that re reinterpret shell syntax and bend over backwards just to not escape quotes ... :/  Anyway, if you insist, then that's it...  Otherwise the PR looks fine, I'll give it a spin later today!

**Comment by marksantcroos** [comment]
> why not double quotes?

What does this refer to now?

**Comment by andre-merzky** [comment]
```
>> so, not using ' but " is not an option?
> Correct.
why not double quotes? 
```

**Comment by marksantcroos** [comment]
To prevent (too) early expansion.

**Comment by marksantcroos** [comment]
This is now implicitly merged via the de-tour.

**Pull request closed without merging**
