### PR TITLE
make use of flags consistent between RP and RS

### PR DESCRIPTION
**Pull request by andre-merzky**
This needs testing...

### CODE REVIEW

**Comment by andre-merzky** [comment]
@vivek-bala : ping

**Comment by vivek-bala** [comment]
Thanks for the reminder Andre! Testing it now. 

Questions:
1) Should 'RECURSIVE' flag from rs.filesystem also be included to rp? Also I believe it can be a default flag in addition to CREATE_PARENTS?
2) I am not entirely sure whether SKIP_FAILED should be the default. The user would expect the task to fail if the data staging failed (prior to execution). When the task fails from 'EXECUTING' state, we expect the executing kernel to have failed due to some computation or resource issues, not due to missing data (which did not get staged in). Would you agree?

**Comment by vivek-bala** [comment]
Tested agent and unit staging. Both working.

**Comment by andre-merzky** [comment]
I'd leave the `recursive` inclusion to one of the RCT class PRs - at the moment its not supported.  But yes, that would be done along the same lines.

The `SKIP_FAILED` is not implemented, AFAIK, and I actually don't know in what use cases that originated.  I would be in favor of removing it to be honest.  But this PR just tries to fix the definitions...  I'll open a ticket for `SKIP_FAILED`.

**Comment by andre-merzky** [comment]
Ticket is #1557

**Comment by vivek-bala** [comment]
Okay. I'll respond on #1557 .

**Comment by andre-merzky** [comment]
Thanks Vivek!

**Pull request merged**
