### PR TITLE
Feature/non fatal missing

### PR DESCRIPTION
**Pull request by marksantcroos**
Fix for #1106, verified by Vivek.

### CODE REVIEW

**Comment by andre-merzky** [comment]
So that only covers input, and only local ops (not transfer).   Shouldn't we do those all in one go?  Happy to take over if you consider that out of scope wrt. your time allotment!

PS.: and I still think `SkipMissing` fits better, as the above code will still be (and should be) fatal on failing ops... ;)

**Comment by marksantcroos** [comment]
I think we have enough real use cases to not solve problems for non-existing use cases. But don't let me stop you.

**Comment by andre-merzky** [comment]
Yeah, I agree in principle, but don't feel very comfortable to introduce a flag which applies sometimes...  Well, I guess such are our different roles now :)

**Comment by marksantcroos** [comment]
Thats easily solved by renaming the flag to `SKIP_MISSING_FILES_ON_AGENT`.
Note that in that case I'm ok with using the word `missing` in it. Anything that is not local I don't think we should try to distinguish missing and failing.

**Comment by andre-merzky** [comment]
Merged now, but I'll keep the ticket open to address the other cases.  Thanks Mark!

**Pull request merged**
