### PR TITLE
move back to python3.7

### PR DESCRIPTION
**Pull request by AymenFJA**
fix issue #2958

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
thanks!

**Comment by eirrgang** [comment]
Would 3.8.8 work?

**Comment by AymenFJA** [comment]
> Would 3.8.8 work?
> 
> E.g. `module load gcc/9.2.0 openmpi/3.1.6 python/3.8.8`

Is `3.8.8` a hard requirement for you?

**Comment by shantenujha** [comment]
Would it not be better to ask Rivanna admins to update to a more "acceptable" version?

**Pull request merged**
