### PR TITLE
recover bootstrap_0_stop event

### LINKED ISSUE #2853: Sometimes `bootstrap_0_stop` event is not recorded
RCT stack:

```
  python               : /home/mturilli/ve/docs/bin/python3
  pythonpath           :
  version              : 3.10.6
  virtualenv           : /home/mturilli/ve/docs

  radical.analytics    : 1.20.1
  radical.entk         : 1.30.0
  radical.gtod         : 1.20.1
  radical.pilot        : 1.22.0-v1.21.0-148-ga004e22d4@devel
  radical.saga         : 1.21.0
  radical.utils        : 1.21.0
```

Apparently, the run exits correctly:

```
$ python het.py het-2048.cfg
new session: [rp.session.mosto.mturilli.019432.0005]                           \
database   : [mongodb://rct-tutorial:****@95.217.193.116:27017/rct-tutorial]  ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   local.localhost        2048 cores     256 gpus           ok
create task manager                                                           ok
submit: ########################################################################
wait  : ########################################################################
	DONE      :  2048
                                                                              ok
closing session rp.session.mosto.mturilli.019432.0005                          \
close task manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                          timeout
                                                                              ok
+ rp.session.mosto.mturilli.019432.0005 (json)
+ pilot.0000 (profiles)
+ pilot.0000 (logfiles)
session lifetime: 888.8s                                                      ok
(docs) mturilli@mosto:~/github/radical.analytics/docs/source/bin$
```

But, the `bootstrap_0_stop` event is missing in `bootstrap_0.prof`:

```
#time,event,comp,thread,uid,state,msg
1678969905.683568,sync_abs,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,mosto:192.168.2.45:1678969905.683568:1678969905.683568:1678969905.683568
1678969905.717970,bootstrap_0_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969906.361555,ve_setup_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969906.502526,ve_activate_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969907.695583,ve_activate_stop,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969907.701869,rp_install_start,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969927.339136,rp_install_stop,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969927.344361,ve_setup_stop,bootstrap_0,MainThread,pilot.0000,pilot_state,
1678969932.811748,bootstrap_0_ok,bootstrap_0,MainThread,pilot.0000,pilot_state,
```

The missing event screws up the calculation of pilot runtime in analytics: `rp.utils.PILOT_DURATIONS_DEBUG['p_agent_runtime']` returns 0. We use that duration to derive the total overheads calculated as the difference between the total time spent running tasks and the time the pilot has been alive.

### PR DESCRIPTION
**Pull request by andre-merzky**
The `bootstrap_0_stop` event is not always recorded, and specifically will be missing if the pilot does not terminate on it's own.  That's all right - but we need to recover that event for later analysis.  This fix implements that functionality: when the profile is read and the event is missing, the event will be inserted into the profile with the timestamp of the last event that pilot has recorded otherwise (usually an `agent.0` heartbeat event).

This fixes #2853

### CODE REVIEW

**Review by mturilli — CHANGES_REQUESTED** [review]
Seeing that we have issues with the profiler quite often, could you add a test for this?

**Comment by andre-merzky** [comment]
> Seeing that we have issues with the profiler quite often, could you add a test for this?

That is already included in the analytics tests.  It's only cumbersome to manually check the plot outputs that's why it was undetected.  Well, I checked this time.  In the long run we should try to find a way to get the plots included here as PR comments (like [this](https://github.com/marketplace/actions/workflow-artifact-pull-request-comment) or [this](https://github.com/gavv/pull-request-artifacts)).

**Comment by mturilli** [comment]
I was wondering about a unit test, not an integration test. For the integration test.

**Review by mturilli — APPROVED** [review]

**Comment by andre-merzky** [comment]
Thanks @mturilli  - unit test is added now.

**Pull request merged**
