### PR TITLE
Feature/pilotdata

### PR DESCRIPTION
**Pull request by andre-merzky**

### CODE REVIEW

**Comment by marksantcroos** [comment]
Why did you move it to docs?

**Comment by andre-merzky** [comment]
Because I would hesitate to expose API which is not implemented.

**Comment by marksantcroos** [comment]
Thats why it is one a branch :-)
Would you mind keeping it as such?

**Comment by andre-merzky** [comment]
Hmm, I don't like branches lying around which do nothing, that is how we ended up with about 30 of them.  But otherwise, sure :)

**Pull request closed without merging**
