### PR TITLE
Hotfix/stampded ibrun

### PR DESCRIPTION
**Pull request by andre-merzky**
This gets the ibrun launch method back into working order on Stampede2.  The PR is needed for RX experiments to function properly: the Gromacs binary used by Srinivas does not like other launch methods.  The PR basically catches up with the changed slots structure.

@mtitov : I assigned this to you, too - but I can't remember if we looked at the slot structure in our previous calls, so let me know if you want to chat about it!

### CODE REVIEW

**Comment by andre-merzky** [comment]
@iparask : any idea where the travis test link went?

**Comment by andre-merzky** [comment]
@iparask : ping

**Comment by iparask** [comment]
I think we need to close the PR and open it again. I do not know what has happened.

**Comment by andre-merzky** [comment]
Going to merge, knowing that the ibrun work on Longhorn will iterate on this code before the next release.

**Pull request merged**
