### PR TITLE
RM Slurm will set `gpus_per_node` if it is not configured

### PR DESCRIPTION
**Pull request by mtitov**

### CODE REVIEW

**Comment by mtitov** [comment]
@eirrgang Eric, would you help to test this with run requiring GPUs?

**Review by andre-merzky — APPROVED** [review]
Thanks @mtitov , LGTM

**Comment by eirrgang** [comment]
> @eirrgang Eric, would you help to test this with run requiring GPUs?

I'll try to get to that soon.

It looks like this change determines the number of GPUs per node _after_ the Pilot job starts. Do I read that correctly? Does a Pilot agent run on all nodes in the job?

It looks like there are from 3 to 10 GPUs per node, depending on the node.

```
$ qlist -p gpu
STATE    NODE           CPUS(A/I/O/T) TOTALMEM(MB)  ALLOCMEM(MB)  AVAILMEM(MB)  GRES(M:T:A)               JOBS
==============================================================================================================
mix      udc-an28-1     28/100/0/128  1000000       28672         971328        gpu:a100:8(S:0-7):8         7
idle     udc-an28-13    0/64/0/64     128000        0             128000        gpu:rtx3090:4(S:0-63:0      0
idle     udc-an28-18    0/64/0/64     128000        0             128000        gpu:rtx3090:4(S:0-63:0      0
drain    udc-an28-24    0/0/64/64     128000        0             128000        gpu:rtx3090:4(S:0-63:0      0
idle     udc-an28-29    0/64/0/64     128000        0             128000        gpu:rtx3090:4(S:0-63:0      0
idle     udc-an28-35    0/64/0/64     128000        0             128000        gpu:rtx3090:4(S:0-63:0      0
drain*   udc-an28-7     0/0/128/128   1000000       0             1000000       gpu:a100:8(S:0-7):0         0
mix      udc-an33-37    15/21/0/36    384000        149072        234928        gpu:v100:4(S:0-1):2         2
mix      udc-an33-38    18/18/0/36    384000        167072        216928        gpu:v100:4(S:0-1):3         3
mix      udc-an34-1     1/127/0/128   2000000       32768         1967232       gpu:a100:8(S:0-7):7         1
mix      udc-an34-13    4/124/0/128   2000000       81920         1918080       gpu:a100:8(S:0-7):4         1
idle     udc-an34-19    0/128/0/128   2000000       0             2000000       gpu:a100:8(S:0-7):0         0
mix      udc-an34-7     10/118/0/128  2000000       65536         1934464       gpu:a100:8(S:0-7):7         1
mix      udc-an36-13    58/70/0/128   2000000       159744        1840256       gpu:a100:8(S:0-7):8         8
mix      udc-an36-19    32/96/0/128   2000000       32768         1967232       gpu:a100:8(S:0-7):8         8
mix      udc-an37-1     28/100/0/128  2000000       397312        1602688       gpu:a100:8(S:0-7):8         2
mix      udc-an37-13    8/120/0/128   2000000       163840        1836160       gpu:a100:8(S:0-7):8         2
mix      udc-an37-19    16/112/0/128  2000000       16384         1983616       gpu:a100:8(S:0-7):7         4
mix      udc-an37-7     16/112/0/128  2000000       16384         1983616       gpu:a100:8(S:0-7):4         4
mix      udc-aw37-33    16/24/0/40    383000        204800        178200        gpu:rtx2080:10(S:0-1:4      4
mix      udc-aw37-37    11/29/0/40    383000        93200         289800        gpu:rtx2080:10(S:0-1:2      2
mix      udc-ba25-23    21/7/0/28     255000        96720         158280        gpu:k80:8(S:0-1):8          6
mix      udc-ba25-24    7/21/0/28     255000        42000         213000        gpu:p100:4(S:0-1):1         1
idle     udc-ba25-25    0/28/0/28     255000        0             255000        gpu:p100:3(S:0-1),gp:0      0
mix      udc-ba25-26    2/26/0/28     255000        49152         205848        gpu:p100:4(S:0-1):2         2
mix      udc-ba25-27    15/13/0/28    255000        60720         194280        gpu:k80:8(S:0-1):7          6
mix      udc-ba25-28    21/7/0/28     255000        126000        129000        gpu:k80:8(S:0-1):3          3
mix      udc-ba26-24    13/15/0/28    255000        48720         206280        gpu:k80:8(S:0-1):5          4
mix      udc-ba26-25    24/4/0/28     255000        228800        26200         gpu:k80:8(S:0-1):4          3
alloc    udc-ba26-26    28/0/0/28     255000        220608        34392         gpu:k80:8(S:0-1):8          5
mix      udc-ba27-23    14/14/0/28    255000        84000         171000        gpu:k80:8(S:0-1):8          8
mix      udc-ba27-24    7/21/0/28     255000        42000         213000        gpu:k80:8(S:0-1):7          7
mix      udc-ba27-26    9/19/0/28     188000        54000         134000        gpu:v100:4(S:0-1):3         3
idle     udc-ba27-27    0/28/0/28     255000        0             255000        gpu:p100:4(S:0-1):0         0
```

**Comment by mtitov** [comment]
@eirrgang thank you for updates, I've also extended GPU checks

> It looks like this change determines the number of GPUs per node _after_ the Pilot job starts. Do I read that correctly? 

Before pilot submission, SAGA might not use `gpus_per_node` and would only require number of requested GPUs (thus to have it in `#SBATCH --gpus=<num_requested_gpus>`, or we can have a special case for Rivanna as `#SBATCH --gres=gpu:<gpu_arch>:<counted_gpus_per_node>`, where `counted_gpus_per_node` could be estimated as `num_requested_gpus /n_nodes`)

After pilot agent is launched, we would need `gpus_per_node` for scheduling, thus RP resource manager will set this parameter.

> Does a Pilot agent run on all nodes in the job?

pilot agent runs on one [batch] node, and that parameter is per job, or am I missing something?

**Comment by mtitov** [comment]
> My concern is that, if the gres specification is not strict enough, the job might land on nodes with different numbers or different types of gpus. This seems like it would be a clumsy way to configure slurm, but I haven't confirmed that it is otherwise.
> In current use cases in Kasson Lab, MD simulations may each use fewer than all cores on a node and fewer than all GPUs on a node, in arbitrary ratios. I'm not sure what sort of heuristic would be best when describing the necessary Pilot in order to place such tasks, or whether there is a significant risk of wasting SUs.

This could be a ground for another PR: (1) evaluate the current approach of requesting GPUs (SAGA layer), (2) extend it if needed with the GPU types, which would be provided as part of resource configuration -> in `system_architecture` (SAGA + RP layers).

> I don't know whether there is a chance that the nodes in the job might be heterogeneous, or what the consequences of that would be. I don't think it is an important feature to allow for, so it might be worth trying to prevent through a more explicit resource request. But it might be appropriate to loop in someone from the UVa research support team.

RP will rely on SLURM settings in case of heterogeneity, since RP would need that configuration for Scheduler only. As part of this evaluation NOOP scheduler could be tested as well - let the system to distribute tasks.

@eirrgang as I understood there is no concerns regarding this PR, but rather further system evaluation, so this PR is ready to go?

**Comment by eirrgang** [comment]
> @eirrgang as I understood there is no concerns regarding this PR, but rather further system evaluation, so this PR is ready to go?

I don't have any suggested edits at this point.

I'll keep an eye on this section of the code when I get a chance to experiment with gpu jobs on rivanna

**Comment by mtitov** [comment]
@eirrgang great! thank you!

**Pull request merged**
