### PR TITLE
Resolving issue #1800.

### PR DESCRIPTION
**Pull request by iparask**
LFS path is checked if it contains environment variables. Otherwise it is left as is.

I does also some PEP8 changes.

### CODE REVIEW

**Comment by itomaldonado** [comment]
Can one of the admins verify this patch?

**Comment by andre-merzky** [comment]
Hmm, I may be missing something - but I think this will not resolve the issue.  The problem is not that there is no `$` in the path string, but that the path is of `NoneType` and thus not iterable.  Your code would have the same exception on the SAGA level I would assume?  The check for `$` is not needed btw:

```
>>> os.path.expandvars('/etc/')
'/etc/'
>>> os.path.expandvars('')
''
>>> os.path.expandvars(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/posixpath.py", line 287, in expandvars
    if '$' not in path:
TypeError: argument of type 'NoneType' is not iterable
```

`dict.get('entry', '')` can still return `None` if somewhere in the past happened `dict['entry'] = None`.  The `get()` will only shield against non-existing keys, not against unset values.  I assume this should be fixed with something like:

```
val = dict.get(key)
if val: 
    val = os.path.expandvars(val)
```

or with:
```
val = dict.get(key)
if val is None:
    val = ''
val = os.path.expandvars(val)
```
whichever you prefer.  The first one is shorter though :-)

**Comment by iparask** [comment]
> `dict.get('entry', '')` can still return `None` if somewhere in the past happened `dict['entry'] = None`. The `get()` will only shield against non-existing keys, not against unset values. I assume this should be fixed with something like:

You are right! I did not think that it may have been set somewhere else as `None`. Let me see where it is set, because it shouldn't. And commit again.

**Comment by andre-merzky** [comment]
We may not have control over where it's set in all cases.  If `expandvars` cannot handle `None`, we should shield... :-/

**Comment by andre-merzky** [comment]
PS.: another option of course is to implement a more resilient `expandvars` routine in RU.  Like, one which works for generic strings, not only paths.  We do something like this already [here](https://github.com/radical-cybertools/radical.utils/blob/version/2/src/radical/utils/config.py#L13) - with a somewhat different syntax, but that could be factored out and expanded...

**Comment by iparask** [comment]
It's been read from `agent_0.cfg`. I think that `lfs_path_per_node` is set to None in that file. I need to see what is going on exactly. I'll answer to the ticket or with a new commit.

**Comment by andre-merzky** [comment]
Remember though that agent configs can be user supplied...

**Pull request merged**
