### PR TITLE
Fix merge error from #2615.

### LINKED ISSUE #2740: Deduplicate deserialization attempt in `worker_mpi.py::_Worker._dispatch_function()`
Somewhere in the history of #2615, the changes from https://github.com/radical-cybertools/radical.pilot/pull/2615/commits/1ffd8ca45db1c0d34b9e885fbcdae1bcd73bc016 had a bad merge,
and the original function structure is mixed with the patched function structure (which intentionally reordered the dispatching attempts, as noted in the docstring).

This means that the "FIXME" purportedly removed by #2615 is still there and the optimization attempted by 1ffd8ca45db1c0d34b9e885fbcdae1bcd73bc016 is just bloat.

A little `git` fu or some inspection should resolve the merge error easily enough, but I don't know when I can get a chance to submit a PR.

### PR DESCRIPTION
**Pull request by eirrgang**
* Reapply 1ffd8ca45db1c0d34b9e885fbcdae1bcd73bc016
* Deduplicate the check for PythonTask values.

Fixes #2740

### CODE REVIEW

**Comment by andre-merzky** [comment]
@AymenFJA : please have a look at this PR.

**Comment by AymenFJA** [comment]
@eirrgang, thanks for this PR. Regarding the `py_task`, the changes are reasonable. For the `worker_mpi` change, I have 2 points:

1. There are inconsistent indentation problems here https://github.com/radical-cybertools/radical.pilot/blob/e4806ba57ef6d517a2c1ccbeef74af2e8084756c/src/radical/pilot/raptor/worker_mpi.py#L624-L641 or the `if/else` are inconsistent (so I do not understand what going on there).
2. Make sure your changes are consistent with our new raptor changes on the worker level (MPI and Default worker)

**Comment by andre-merzky** [comment]
> 1. the `if/else` are inconsistent

The `else` is part of the `try/except/else` clause if I am not mistaken.

> 2. Make sure your changes

I think this is our fault: we had this PR linger for so long that it now conflicted with the dispatcher refactoring.  @AymenFJA: can you please have a look at the [original commit in this PR](https://github.com/radical-cybertools/radical.pilot/pull/2800/commits/f7ce11afa9a8392218c89e8af2e7a1ea2e2168d5) and maybe backport that to the current raptor code?  That is a fairly small changeset AFAICT.

**Comment by eirrgang** [comment]
> > 1. the `if/else` are inconsistent
> 
> The `else` is part of the `try/except/else` clause if I am not mistaken.

Correct. That block uses `_args` and `_kwargs`, which are only defined if the `try:` succeeded. But we want to `except` and branch after the minimal amount of code that will raise the exception we're anticipating, and which affects our control flow.

**Comment by andre-merzky** [comment]
ping @AymenFJA

**Comment by eirrgang** [comment]
> I think this is our fault: we had this PR linger for so long that it now conflicted with the dispatcher refactoring. @AymenFJA: can you please have a look at the [original commit in this PR](https://github.com/radical-cybertools/radical.pilot/pull/2800/commits/f7ce11afa9a8392218c89e8af2e7a1ea2e2168d5) and maybe backport that to the current raptor code? That is a fairly small changeset AFAICT.

I think I got it.

**Comment by andre-merzky** [comment]
ping @AymenFJA

**Review by andre-merzky — APPROVED** [review]
LGTM

**Pull request merged**
