### PR TITLE
switch to new OMPI deployment

### PR DESCRIPTION
**Pull request by andre-merzky**
the original OMPI deployment got purged - this is the replacement.

### CODE REVIEW

**Comment by andre-merzky** [comment]
Hey Jumana, as per last call, please give this a try on Titan.  This should be merged quickly once I get confirmation that it works for anybody else than just me.  Thanks!

**Comment by andre-merzky** [comment]
@jdakka : ping :-)

**Comment by jdakka** [comment]
Some of the examples work, but others I get `caught Exception: 'NoneType' object has no attribute 'strip'` errors. I tested with the new Titan project allocation from INSPIRE.

**Comment by andre-merzky** [comment]
@jdakka: ping : is this waiting for action on me?  If so, please provide more specifics on what fails, and why you think its related to the PR.  Thanks!

**Comment by jdakka** [comment]
Using `devel` for `S/RU, and `titan_orte`config. 

Examples are failing: 
```
Traceback (most recent call last):
  File "01_unit_details.py", line 109, in <module>
    unit.exit_code, unit.stdout.strip()[:35]))
AttributeError: 'NoneType' object has no attribute 'strip'
```
I've attached the client files. It looks like it's failing at PMGR: `pilot.0000', 'ornl.titan_orte', 'FAILED'`  

[orte_ompi.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1703567/orte_ompi.tgz.zip)

**Comment by andre-merzky** [comment]
For the first session, the pilot sandbox is empty, the second session has no pilot sandbox.  Is that what you see on titan?  If not, can you please add the pilot sandboxes?  Thanks!

**Comment by andre-merzky** [comment]
Uh, this is a very unexpected error, and totally unrelated to the change in this PR.  I will have to add some code to the bootstrapper to track this down...

**Comment by andre-merzky** [comment]
done - can you please update RP and run another test - please sens the resulting pilot sandbox on failure again.  Thanks!

**Comment by jdakka** [comment]
Doesn't appear to be fixed :/ 
[rp.session.titan-ext5.jdakka.017572.0003_agent.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1713855/rp.session.titan-ext5.jdakka.017572.0003_agent.tgz.zip)
[rp.session.titan-ext5.jdakka.017572.0003_client.tgz.zip](https://github.com/radical-cybertools/radical.pilot/files/1713856/rp.session.titan-ext5.jdakka.017572.0003_client.tgz.zip)

**Comment by andre-merzky** [comment]
Jumana, are there any changes in your config files, or do you have any additional configs in `~/.radical/pilot/configs/` ?

**Comment by andre-merzky** [comment]
Also, do you have access to other projects on titan than `chm126`?  Which ones?  Can you try using another project, please?

**Comment by andre-merzky** [comment]
Last one for now: can you please switch to `fix/issue_rp_1528` for `radical.utils`?

**Comment by jdakka** [comment]
@andre-merzky I do not modify the `resource_ornl.json`. I'm afraid I do not have access to another allocation on Titan. Will test out with `fix/issue_rp_1528`

**Comment by andre-merzky** [comment]
The branch switch is unlikely to help with this specific problem :(  Can you please send me the output of `groups` from a shell on titan?

**Comment by jdakka** [comment]
`(venv) jdakka@titan-ext5:/lustre/atlas/scratch> groups`
`jdakka chm126`

**Comment by andre-merzky** [comment]
Jumana, this problem seems unrelated to the PR at hand - let me reassign the PR testing, and we iterate further on a ticket, ok?

**Comment by andre-merzky** [comment]
Reassigned to @vivek-bala , ticket is at #1559.

**Pull request merged**
