### PR TITLE
Fixed values for requested resources

### PR DESCRIPTION
**Pull request by mtitov**
TBD
- [x] tests
- [x] config for `rutgers.amarel`

(*) updates are related to the discussion [here](https://github.com/radical-cybertools/radical.pilot/pull/2760#issuecomment-1298576685)

### CODE REVIEW

**Comment by mtitov** [comment]
@AymenFJA can you please test this branch on Amarel

**Comment by AymenFJA** [comment]
Hey @mtitov , I just tested it and it passed on `Amarel`: 

```shell
(conda_rnaseq) [afa64@amarel1 examples]$ python 00_getting_started.py 

================================================================================
 Getting Started (RP version 1.18.1)                                            
================================================================================

new session: [rp.session.amarel1.amarel.rutgers.edu.afa64.019298.0000]         \
database   : [mongodb://aymen:****@95.217.193.116:27017/radical3]             ok
create pilot manager                                                          ok
create task manager                                                           ok

--------------------------------------------------------------------------------
submit pilots                                                                   

submit 1 pilot(s)
        pilot.0000   rutgers.amarel           16 cores       0 gpus           ok

--------------------------------------------------------------------------------
submit 10 tasks                                                                 

create: ########################################################################
submit: ########################################################################
wait  : ########################################################################
        DONE      :    10
                                                                              ok

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.amarel1.amarel.rutgers.edu.afa64.019298.0000        \
close task manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                          timeout
                                                                              ok
+ rp.session.amarel1.amarel.rutgers.edu.afa64.019298.0000 (json)
+ pilot.0000 (profiles)
+ pilot.0000 (logfiles)
session lifetime: 96.3s                                                       ok

--------------------------------------------------------------------------------

(conda_rnaseq) [afa64@amarel1 examples]$ radical-stack 

  python               : /cache/home/afa64/miniconda3/envs/conda_rnaseq/bin/python3
  pythonpath           : 
  version              : 3.8.8
  virtualenv           : conda_rnaseq

  radical.entk         : 1.18.0
  radical.gtod         : 1.16.0
  radical.pilot        : 1.18.1-v1.18.1-178-g750d27c@fix-requested_resources
  radical.saga         : 1.18.0
  radical.utils        : 1.18.1
```

**Review by AymenFJA — APPROVED** [review]
LGTM thanks @mtitov

**Review by andre-merzky — APPROVED** [review]
LGTM also - thanks!

**Comment by mtitov** [comment]
perfect! thank you both!

**Pull request merged**
