### PR TITLE
Hotfix/tags

### PR DESCRIPTION
**Pull request by andre-merzky**
forward compatibility for tags - see radical-cybertools/radical.entk/issues/429

### CODE REVIEW

**Review by iparask — APPROVED** [review]
I'm approving of the change since I know it works! I'll try to create a test case for tags.

**Comment by andre-merzky** [comment]
>  I'll try to create a test case for tags.

Thank you!

**Comment by iparask** [comment]
@andre-merzky I added the test case. I'll do more while writing more tests.

**Comment by andre-merzky** [comment]
> @andre-merzky I added the test case. I'll do more while writing more tests.

Is this good to merge, or should we wait for those other tests?

**Comment by iparask** [comment]
I see that one of the tests fails. After that is fixed we can merge and I will add tests during my testing day. :)

**Comment by andre-merzky** [comment]
> I see that one of the tests fails. After that is fixed we can merge and I will add tests during my testing day. :)

This should be fixed now.  I don't see how the test can have worked before though: the unit fed into the scheduler is `unit.000000`, but the test checks if the tag history has been filled for `unit.000001`?

**Pull request merged**
