### PR TITLE
Hotfix/832

### PR DESCRIPTION
**Pull request by andre-merzky**
#832 reports this fix as functional.

### CODE REVIEW

**Comment by marksantcroos** [comment]
Its ready to review and merge.

**Comment by andre-merzky** [comment]
Looks good to me.  Only comment: the 42 is obviously not  arbitrary, but also not really sensible (apart from being the only sensible answer).  Is there any way to estimate the actual borderline value?

**Comment by marksantcroos** [comment]
The underlying value is either max number of parameters or max command line length. 42 was in the right ballpark and therefore an obvious choice ;)

**Comment by andre-merzky** [comment]
Good enough for me :)

**Pull request merged**
