### PR TITLE
Feature/mpi raptor tutorial

### PR DESCRIPTION
**Pull request by AymenFJA**
Adding RAPTOR MPI tutorial to `raptor.ipynb` (related to #3040 )

### CODE REVIEW

**Comment by mturilli** [comment]
@AymenFJA , did we agreed to create a separate Notebook so to separate a possible failure of the non-MPI RAPTOR worker from those of the MPI worker? I remember we discussed that but I may be wrong about the agreed upon conclusion.

**Comment by AymenFJA** [comment]
> @AymenFJA , did we agreed to create a separate Notebook so to separate a possible failure of the non-MPI RAPTOR worker from those of the MPI worker? I remember we discussed that but I may be wrong about the agreed upon conclusion.
@mturilli Ok, there might be some misunderstanding. Happy to create a separate notebook with the tutorial of RAPTOR MPI only.

**Comment by mturilli** [comment]
@AymenFJA thanks. Pls check why multipilot is failing, checking the sessions of the notebook by downloading them from the (summary) of the run action.

**Comment by AymenFJA** [comment]
@mturilli two points here: 

1. Did we turn off the logs of the session in our tests on purpose as all of the `*.log` files are empty in the session folder?
2. It seems like the sessions did not fail actually as I checked the tasks and the ran fine and produced output. The failure comes from converting the session into a notebook: 
```
Run . testenv/bin/activate
[NbConvertApp] Converting notebook docs/source/tutorials/multiple_pilots.ipynb to notebook
[NbConvertApp] Writing 12299 bytes to docs/source/tutorials/multiple_pilots.ipynb
[NbConvertApp] Converting notebook docs/source/tutorials/multiple_pilots.ipynb to notebook
Error: The action has timed out.
```

**Comment by mtitov** [comment]
@AymenFJA debug messages are within sandboxes, thus you are able to go through failed run

**Comment by AymenFJA** [comment]
The PR tests are failing with `no module named mpi4py` on the raptor worker level. The reason is that we need to instruct our pilot to create an env with `mpi4py` installed in it. We will update the tutorial with how to do that. This will also make the user aware of this possibility.

**Review by mturilli — APPROVED** [review]
Thanks!

**Comment by mtitov** [comment]
@AymenFJA RAPTOR tutorial need to be reset, it happened you merged it with executed cells. Please create another PR for that (and can you please also do the same for "Configuration" tutorial in that PR)

**Pull request merged**
