### PR TITLE
Feature/entk 259

### PR DESCRIPTION
**Pull request by andre-merzky**
Expose pilot staging area env to units

### CODE REVIEW

**Comment by mturilli** [comment]
This is marked as priority high but has been open for 6 months now.

**Comment by andre-merzky** [comment]
This is also waiting on reviews - needs confirmation that the original issue is addressed with this patch.

**Comment by vivek-bala** [comment]
Apologies, this was tested and the original EnTK has been closed. This PR can be merged+closed.

**Comment by andre-merzky** [comment]
Thanks Vivek!

**Pull request merged**
