### PR TITLE
Option `--ppn` in MPIEXEC LM

### PR DESCRIPTION
**Pull request by mtitov**

### CODE REVIEW

**Comment by mturilli** [comment]
@GKNB does this PR implements the behavior you expected?

**Comment by andre-merzky** [comment]
> @GKNB does this PR implements the behavior you expected?

ping?

**Comment by GKNB** [comment]
I think this branch is also consistent with the main devel branch now, and in the main devel branch I can see a --ppn flag is already added for each task and it runs successfully for the mini-app, so I think it works fine.

**Comment by mtitov** [comment]
confirmed with the test run on Polaris

**Review by andre-merzky — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
