### PR TITLE
alternative approach to import check

### PR DESCRIPTION
**Pull request by andre-merzky**
not tested, just illustrative...

### CODE REVIEW

**Comment by andre-merzky** [comment]
Any opinion on that approach? :)

**Comment by marksantcroos** [comment]
Yes :)

**Comment by andre-merzky** [comment]
Care to share it? ;)  I mean, beyond the button press... :P

**Comment by marksantcroos** [comment]
I dont consider changing the decorators a feature.

**Comment by andre-merzky** [comment]
on code which is not running anyway?  Hmm...

**Pull request closed without merging**
