### PR TITLE
Resolving issue #1211.

### PR DESCRIPTION
**Pull request by iparask**
This is the PR based on the above mentioned ticket.

### CODE REVIEW

**Comment by andre-merzky** [comment]
Thanks a bunch, Iannis!  I assume that George tested and confirmed that it works?

**Comment by iparask** [comment]
Yes, check the ticket

**Comment by andre-merzky** [comment]
Ah, right, great! :)

**Comment by iparask** [comment]
I am closing this PR as it was merged with the devel branch. 

Just for the record, the bootstrapped checks whether the installation is for Anaconda python or not. In the case that it is not, it updates setuptools and pip to the versions that are specified. If RP is installed over Anaconda python distribution no update occurs

**Pull request merged**
