### PR TITLE
v0.47

### PR DESCRIPTION
**Pull request by andre-merzky**

### CODE REVIEW

**Comment by itomaldonado** [comment]
Tests still hang on example 07: `python 07_shared_unit_data.py`

**Comment by vivek-bala** [comment]
Is the execution 'hanging' same as #1433 ? I see that the shared unit data example has both pilot and unit staging.

**Comment by itomaldonado** [comment]
@andre-merzky did you merge the fix for hanging execution?

**Comment by andre-merzky** [comment]
Merged now.  I was waiting for a review from Iannis, but I am not sure he got the note... :P

**Comment by iparask** [comment]
I am not assigned as a reviewer, Manuel is. As a result I did not get a notification. Did we discuss this?

**Comment by andre-merzky** [comment]
@iparask : This referred to the staging PR (#1508).  I should have pinged you, sorry!  But don't worry about it now, @itomaldonado looked through it already (had assigned him, too).

**Comment by andre-merzky** [comment]
Hmm, Jenkins still doesn't like us.  I feel rejected...

**Comment by itomaldonado** [comment]
@andre-merzky I went ahead and kicked-off an ad-hoc test for this PR. Seems to work. Will kick-off the ad-hoc again so it changes the status here and we should be good to go.

**Comment by itomaldonado** [comment]
Jenkins please test this

**Comment by itomaldonado** [comment]
Jenkins test this please

**Pull request merged**
