### PR TITLE
Fix/session termination

### PR DESCRIPTION
**Pull request by andre-merzky**
This seems to work *much* better than before...  Tests done on active cancellation in various pilot states, on various machines, but because of the convoluted worker dependencies in the RP module, its  difficult to do an exhaustive set of tests...

### CODE REVIEW

**Comment by marksantcroos** [comment]
On a failing pilot startup:
```
2015-09-22 05:26:46,103: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well

2015-09-22 05:27:46,435: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [torque://localhost]-[2488363])
2015-09-22 05:27:46,457: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : SAGA job state for ComputePilot pilot.0000 is Done.
2015-09-22 05:27:46,457: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: WARNING : pilot pilot.0000 declared dead
2015-09-22 05:27:46,748: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'PendingActive' to 'Done'.
[Callback]: ComputePilot 'pilot.0000' state: Done.

```

**Comment by marksantcroos** [comment]
And on a successful completion of the agent:
```
2015-09-22 05:34:57,853: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-09-22 05:34:57,854: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : pilot launching is disabled
2015-09-22 05:34:58,855: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : pilot launching is disabled
2015-09-22 05:34:59,856: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : pilot launching is disabled
2015-09-22 05:35:00,233: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'Active' to 'Failed'.
[Callback]: ComputePilot 'pilot.0000' state: Failed.

STDOUT: None



STDERR: None



LOG   : [<radical.pilot.logentry.Logentry object at 0x2b9681371750>, <radical.pilot.logentry.Logentry object at 0x2b9681371f50>, <radical.pilot.logentry.Logentry object at 0x2b9682842f10>, <radical.pilot.logentry.Logentry object at 0x2b9682842c10>, <radical.pilot.logentry.Logentry object at 0x2b9682842ad0>, <radical.pilot.logentry.Logentry object at 0x2b9682842b90>, <radical.pilot.logentry.Logentry object at 0x2b9682842f50>, <radical.pilot.logentry.Logentry object at 0x2b9682842e10>, <radical.pilot.logentry.Logentry object at 0x2b9682842f90>, <radical.pilot.logentry.Logentry object at 0x2b9682c5c190>, <radical.pilot.logentry.Logentry object at 0x2b9682c5c210>, <radical.pilot.logentry.Logentry object at 0x2b9682c5c150>, <radical.pilot.logentry.Logentry object at 0x2b9682c5c050>, <radical.pilot.logentry.Logentry object at 0x2b9682c5c1d0>]


2015-09-22 05:35:00,233: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 328, in run
    self.call_callbacks(pilot_id, new_state)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 249, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "test_mpi.py", line 25, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
2015-09-22 05:35:00,238: radical.pilot       : MainProcess                     : Thread-1       : DEBUG   : pworker Thread-1 stops   launcher PilotLauncherWorker-1
2015-09-22 05:35:00,238: radical.pilot       : MainProcess                     : Thread-1       : DEBUG   : launcher PilotLauncherWorker-1 stopping
2015-09-22 05:35:00,857: radical.pilot       : MainProcess                     : Thread-1       : DEBUG   : launcher PilotLauncherWorker-1 stopped
2015-09-22 05:35:00,858: radical.pilot       : MainProcess                     : Thread-1       : DEBUG   : pworker Thread-1 stopped launcher PilotLauncherWorker-1
Traceback (most recent call last):
  File "test_mpi.py", line 203, in <module>
    run_test (cfg)
  File "test_mpi.py", line 160, in run_test
    session.close (cleanup=False)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/session.py", line 277, in close
    pmgr.close (terminate=terminate)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 168, in close
    self.cancel_pilots()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 485, in cancel_pilots
    self._worker.register_cancel_pilots_request(pilot_ids=pilot_ids)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 550, in register_cancel_pilots_request
    time.sleep (10)
KeyboardInterrupt
>
```

Ugly is an understatement, but at least it returns!

**Comment by andre-merzky** [comment]
My guess would be that this is one of those cases where the job info are reaped quickly and we can't get the correct state on SAGA level? This is the only code path leading to a `DONE` for the pilot:

https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/controller/pilot_launcher_worker.py#L183

and the log specifically reports the SAGA state as `DONE`.  May need  fixing, but not in this PR.

What this PR also does not fix is that `CANCELED` pilots are sometimes reported as `FAILED`.

**Comment by andre-merzky** [comment]
Ah, right, I wanted to remove the stack traces.  Is that  successful completion a 'cancel' or 'timeout'?   Timeout indeed should go into DONE, I would try to fix that.  I am not sure I want to address the `CANCELED`/`FAILED` state confusion in  the scope of this PR...

**Comment by andre-merzky** [comment]
Nah, I think I'll have to leave the traces for now -- doing a clean intercept on the callback invoked sys.exit's opens quite a can of worms...

**Comment by marksantcroos** [comment]
> My guess would be that this is one of those cases where the job info are reaped quickly and we can't get the correct state on SAGA level?

Nope, it stays around for quite a bit after everything completes. That doesn't rule out a SAGA layer problem of course.

**Comment by marksantcroos** [comment]
> Is that successful completion a 'cancel' or 'timeout'?

RP client 'cancel' as otherwise Im not sure if I would call it successful ... :)

**Comment by andre-merzky** [comment]
> Nope, it stays around for quite a bit after everything completes. That doesn't rule out a SAGA layer problem of course.

```
2015-09-22 05:27:46,457: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : SAGA job state for ComputePilot pilot.0000 is Done.
```
is very explicit.  This is literally the SAGA state (see https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/controller/pilot_launcher_worker.py#L186)

> RP client 'cancel' as otherwise Im not sure if I would call it successful ... :)

Well, we do declare the pilot `DONE`  when it hits timeout:  https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L6020

**Comment by marksantcroos** [comment]
> is very explicit. This is literally the SAGA state (see https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/controller/pilot_launcher_worker.py#L186)

Then I don't understand the initial point you wanted to make.

**Comment by marksantcroos** [comment]
> Well, we do declare the pilot DONE when it hits timeout: https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L6020

That might well be, but in most cases this would mean that the workload didn't complete.

**Comment by andre-merzky** [comment]
>> is very explicit. This is literally the SAGA state (see https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/controller/pilot_launcher_worker.py#L186)

> Then I don't understand the initial point you wanted to make.

You reported that a failed bootstrap ended in a `DONE` state.  My assumption was that you considered that an error, because otherwise you would not have reported it?  My reply is basically: true, but that is a SAGA error, and will not be fixed in this pull request.

**Comment by marksantcroos** [comment]
> You reported that a failed bootstrap ended in a DONE state.

No, I reported that a failed agent made the client hang.

**Comment by marksantcroos** [comment]
> Ugly is an understatement, but at least it returns!

With the "elif" fix, it doesn't only consistently return now, but also cleanly. Jay!

**Comment by andre-merzky** [comment]
>> Well, we do declare the pilot DONE when it hits timeout: https://github.com/radical-cybertools/radical.pilot/blob/fix/session_termination/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L6020

> That might well be, but in most cases this would mean that the workload didn't complete.

I do agree with you, but I brought that up multiple times already, and so far found no agreement on *not* moving a timed-out pilot to `DONE`.  I would not mind changing that definition, really (even if that leaves us with no `DONE` state on the pilot at all).

**Comment by andre-merzky** [comment]
> No, I reported that a failed agent made the client hang.

Well, that was not obvious at all...  

how long did you let it run?  the pilot state change needs a while to trickle through to the pilot manager.  I'll try to reproduce it.

**Comment by marksantcroos** [comment]
> and so far found no agreement on not moving a timed-out pilot to DONE

And for good reasons. A Pilot that did what it was supposed to (i.e. run for a certain amount of time) is DONE. That's regardless of any workload semantics.

**Comment by marksantcroos** [comment]
> how long did you let it run?

Minutes. Was that too impatient?

**Comment by andre-merzky** [comment]
No, not at all.

I can't reproduce this though: a pilot which exit's in the bootstrapper is correctly detected as `FAILED` for me.  What exactly did you run where?

**Comment by andre-merzky** [comment]
I think you need to restart the DONE/timeout/canceled thread, if you think that is still relevant.  I am very confused, as your statements seem contradictory?

**Comment by marksantcroos** [comment]
> What exactly did you run where?

Nothing special on Titan. Just ran it again.

```
2488390                 marksant1   batch    SAGA-Python-TORQ   4900     3     48    --   00:30:00 C       --
```

```
2015-09-22 07:44:03,239: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : SAGA job submitted with job id [torque://localhost]-[2488390]
2015-09-22 07:44:03,458: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'Launching' to 'PendingActive'.
[Callback]: ComputePilot 'pilot.0000' state: PendingActive.
2015-09-22 07:44:55,433: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [torque://localhost]-[2488390])
2015-09-22 07:44:58,455: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : SAGA job state for ComputePilot pilot.0000 is Done.
2015-09-22 07:44:58,455: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: WARNING : pilot pilot.0000 declared dead
2015-09-22 07:44:58,707: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'PendingActive' to 'Done'.
[Callback]: ComputePilot 'pilot.0000' state: Done.
```

**Comment by marksantcroos** [comment]
> your statements seem contradictory?

Which ones?

**Comment by marksantcroos** [comment]
> Nothing special on Titan. Just ran it again.

To be more precise, the error I emulate is that the install fails in bootstrapper_1 at:
https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/bootstrapper/default_bootstrapper.sh#L1048

**Comment by andre-merzky** [comment]
>> your statements seem contradictory?

> Which ones?

those:

> RP client 'cancel' as otherwise Im not sure if I would call it successful ... :)

> That might well be, but in most cases this would mean that the workload didn't complete.

> A Pilot that did what it was supposed to (i.e. run for a certain amount of time) is DONE. That's regardless of any workload semantics.

Those seem exclusive to me, so I probably misinterpreted the context or something.  But, as said, don't bother if that is not relevant anymore...

**Comment by marksantcroos** [comment]
>> RP client 'cancel' as otherwise Im not sure if I would call it successful ... :)
> >
>> That might well be, but in most cases this would mean that the workload didn't complete.
> >
> >A Pilot that did what it was supposed to (i.e. run for a certain amount of time) is DONE. That's regardless of any workload semantics.

> Those seem exclusive to me, so I probably misinterpreted the context or something. But, as said, don't bother if that is not relevant anymore...

Ok, the former comment was in the context of applications, the latter for an individual pilot.

**Comment by andre-merzky** [comment]
I can't run on titan, but have something in the queue on india, which is also torque.  Not sure if that matters, really, as this is after SAGA state reporting, but so far I could not reproduce it, neither locally nor on  slurm.  I have an 'exit' earlier in the bootstrapper, that should be similar enough.

**Comment by andre-merzky** [comment]
and the middle one in between I guess :D

But, is there anything wrong with the states at this point, apart from the hang?

**Comment by marksantcroos** [comment]
So, lets step back.

1. The failed pilot being reported as `DONE` is obviously a SAGA bug and doesn't require debugging in RP. 
The `exit_status` is set to `1` but the adaptor still translates it to `DONE` instead of `FAILED`.

2. The "hanging" of the application, thats likely a problem between my chair and my keyboard, as there is no magic action defined of what to do when a pilot is `DONE` (because of clause 1) before the workload is completed.

So I think I created confusion because of 2, but 1 is still a problem that needs fixing.

**Comment by andre-merzky** [comment]
Ack on both.  1 needs fixing on SAGA level though,  right?

**Comment by marksantcroos** [comment]
> Ack on both. 1 needs fixing on SAGA level though, right?

Yes. Sorry if that was what you were trying to say all along.

**Comment by andre-merzky** [comment]
ack :)

**Pull request merged**
