### PR TITLE
printf vs. echo  fixes

### PR DESCRIPTION
**Pull request by andre-merzky**
`printf` interprets `%` which is not always wanted, for example when a shell script is passed as argument.    Echo is not always interpreting `\n` correctly, thus equally corrupting scripts passed as arguments.  We thus wrap `printf` in a function which makes sure that `%` are escaped correctly, thus maintaining `\n` interpretation, and avoiding the printf expansion.

### CODE REVIEW

**Comment by marksantcroos** [comment]
This is the same fix I verified in a different branch already, right?

**Comment by andre-merzky** [comment]
Yes, I think so.

**Comment by marksantcroos** [comment]
Ok, then I consider them tested.

**Comment by marksantcroos** [comment]
Thanks

**Pull request merged**
