### PR TITLE
Fix/cheyenne

### PR DESCRIPTION
**Pull request by vivek-bala**
Created a new VE on Cheyenne -- updated config
Some fixes in the RM and changes in the LM to adhere to new nodelist format for mpirun_mpt launch method

### CODE REVIEW

**Comment by itomaldonado** [comment]
Can one of the admins verify this patch?

**Comment by vivek-bala** [comment]
Note that the VE (specified in the config) is currently held under my account on Cheyenne. Was created with
```
module load python/2.7.15
radical-pilot-create-static-ve ve.rp.cheyenne.2019.02.07
```

**Comment by mturilli** [comment]
@andre-merzky Ready to merge?

**Comment by vivek-bala** [comment]
I think this might be already merged? I'll check with Weiming, he might be using devel.

**Comment by andre-merzky** [comment]
Please don't use devel right now - that depends on devel in  RU ans RS.

Let me review this (looks good on first glance), and I push out a release.

**Comment by vivek-bala** [comment]
Correct. He is using fix/cheyenne:
```
> radical-stack 

  python               : 2.7.15
  pythonpath           : 
  virtualenv           : /gpfs/u/home/wuh20/github/hpc-workflows/scripts/application_AnEn/year_2/multi-node/venv

  radical.entk         : 0.7.12
  radical.pilot        : 0.50.21-v0.50.21-2-gbfedd8f@fix-cheyenne
  radical.utils        : 0.50.3
  saga                 : 0.50.5
```

**Comment by andre-merzky** [comment]
Cheyenne system limit make it difficult to run, otherwise this is complete.

**Pull request merged**
