### PR TITLE
let units fail on pre/post exec errors

### LINKED ISSUE #1240: What happens if pre_exec fails?
Hello,

I think that if pre_exec fails in a CU the execution of the CU will continue. Am I correct? 

If yes, shouldn't the CU fails since one condition for its execution is not met?

In all of these, I am assuming that the executable will run correctly, whether the pre_exec conditions are met or not.

Thank you
Giannis

### PR DESCRIPTION
**Pull request by andre-merzky**
fixes #1240, in that it makes the CU execution fail on pre- and post-exec errors.  This PR implements this for the popen and shell spawners, and documents it for orte.  Yarn and ABDS should be checked fro consistency - I'll reassign the ticket to Iannis once this PR is merged.

In general: we are sharing lots of code for the script generation between the launch methods, and probably should move parts of it into RP-utils, to simplify maintenance and increase consistency.  At this point, ORTE-LIB is the only LM which really looks fundamentally different I think.

### CODE REVIEW

**Comment by itomaldonado** [comment]
This next line will trigger Jenkins to re-test:

jenkins test this please

**Comment by itomaldonado** [comment]
jenkins test this please

**Comment by andre-merzky** [comment]
jenkins test this please

**Comment by andre-merzky** [comment]
jenkins test this please

**Comment by andre-merzky** [comment]
jenkins test this please

**Comment by andre-merzky** [comment]
jenkins test this please

**Comment by andre-merzky** [comment]
jenkins test this please

**Comment by iparask** [comment]
The CU failed with wrong pre_exec and post exec. The respective mesasges

```
pre_exec failed
```
```
Sun May 28 15:45:31 CDT 2017
post_exec failed
```
I think it is okay!

**Pull request merged**
