### PR TITLE
Fix/bw stacksize

### PR DESCRIPTION
**Pull request by andre-merzky**

### CODE REVIEW

**Comment by andre-merzky** [comment]
@vivek-bala , can you please give this branch a try on BW?  As soon as you confirm that this works for you, I'll push out a hotfix release.  Thanks!

**Comment by andre-merzky** [comment]
ping @vivek-bala .  @jdakka : Jumana, would you mind checking this out in case Vivek does not find the time?  I would liketo push this one out rather sooner than later...

**Comment by jdakka** [comment]
Tested `00_getting_started.py`, worked! 

Attached are session folders: 

Agent logs: `/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017816.0002/pilot.0000`

Client logs: 
[rp.session.two.jdakka.017816.0002.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2474361/rp.session.two.jdakka.017816.0002.tar.gz)

**Comment by andre-merzky** [comment]
Thanks Jumana!

**Pull request merged**
