### PR TITLE
disable env inheritance in PSIJ launcher

### PR DESCRIPTION
**Pull request by andre-merzky**

### CODE REVIEW

**Comment by mturilli** [comment]
Needs to take into account when inheritance is actually needed.

**Comment by mtitov** [comment]
Should be considered that disabling env inheritance is for the batch script, but it is recommended to reset it inside the execution environment, since corresponding launch methods might reuse (specifically the case for SBATCH and SRUN) options set by the batch script

Slurm example
```
...
#SBATCH --export  NONE

unset SLURM_EXPORT_ENV
```

**Comment by andre-merzky** [comment]
This should be ready for another review.

**Review by mtitov — APPROVED** [review]
LGTM!

**Pull request merged**
