### PR TITLE
Fix/ve misc

### PR DESCRIPTION
**Pull request by marksantcroos**
This makes OSG work again.

### CODE REVIEW

**Comment by andre-merzky** [comment]
FWIW, it is annoying that a failing bootstrap is not resulting in a `FAILED` pilot, but one basically only find out about the failure by looking at the remote logfiles...

**Comment by andre-merzky** [comment]
Otherwise the dir permission problem seems  gone - YAY!  I do end up with: bootstrap_1.sh this though:

```
 line 83: cc: command not found
```

any advise?

**Comment by marksantcroos** [comment]
> FWIW, it is annoying that a failing bootstrap is not resulting in a FAILED pilot, but one basically only find out about the failure by looking at the remote logfiles...

You mean because the jobs goes into `HOLD` or in general?

**Comment by marksantcroos** [comment]
> line 83: cc: command not found
> any advise?

Yes, blacklist the site similar as https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/getting_started_osg.py#L123

You need to get the `GLIDEIN_Site` entry from bootstrap_1.out.

**Comment by andre-merzky** [comment]
> You mean because the jobs goes into HOLD or in general?

Yes, it goes into `HOLD` and never leaves (or so it seems).  But the bootstrapper clearly failed at this point.  I think we discussed this, you said Condor is waiting for output files which will never appear.  Should we 'touch' them in the bootstrapper?  Is there any other way to get things unstuck?  Leaving it stuck does not seem like an option, really...

**Comment by andre-merzky** [comment]
> blacklist...

Ah: that line was disabled in the branch.  Lets see how that goes...  Thanks!

**Comment by marksantcroos** [comment]
> Yes, it goes into HOLD and never leaves (or so it seems). But the bootstrapper clearly failed at this point. I think we discussed this, you said Condor is waiting for output files which will never appear. Should we 'touch' them in the bootstrapper? Is there any other way to get things unstuck? Leaving it stuck does not seem like an option, really...

Right, this falls in the 80% part of getting OSG to work :)

**Comment by marksantcroos** [comment]
> Ah: that line was disabled in the branch. Lets see how that goes... Thanks!

I'll start to create separate tickets for these site specific issues.

**Comment by andre-merzky** [comment]
Thanks!

**Comment by andre-merzky** [comment]
This seems to work nicely now - thanks!

**Pull request merged**
