### PR TITLE
Feature/yarn

### PR DESCRIPTION
**Pull request by andre-merzky**
Iannis, George, 

the changes in this branch seem relatively minor, and are localized to the yarn files.  Should this be merged?  The branch is idle since quite some time.  If merge doesn't make sense, what is the plan for this branch?

Thanks, Andre.

### CODE REVIEW

**Comment by iparask** [comment]
Please do merge it. If you want to delete it, go ahead. I will create it again if it is needed.

**Comment by iparask** [comment]
I merged the YARN branch with devel. I did run my test also.

**Comment by andre-merzky** [comment]
thanks!

**Comment by andre-merzky** [comment]
Soo, now that we have yarn merged - what is the state of feature/spark? :)

**Pull request merged**
