### PR TITLE
Multiple Pilots Example & Docs

### PR DESCRIPTION
**Pull request by iparask**

### CODE REVIEW

**Comment by iparask** [comment]
It worked after creating the ssh config based on #743

**Comment by andre-merzky** [comment]
Thanks for the PR, Iannis!   If you don't mind, would you please re-create it, and make the PR toward branch `release/v0.37`?  Alas, the target branch for a PR cannot be changed AFAIK, so you'd have to re-create it...  Thanks!

**Comment by iparask** [comment]
So I am closing this PR (pull request?) and create a new one for the release/v0.37 branch? Right?

It is a bit difficult with the abbreviations..... :P

**Comment by marksantcroos** [comment]
ACK ;-)

**Comment by andre-merzky** [comment]
Iannis -- I'll close this one and reopen it toward the 0.37 branch, for merge, ok?  Thanks!

**Pull request closed without merging**
