### PR TITLE
    rename LRMS to RM

### PR DESCRIPTION
**Pull request by andre-merzky**
The naming of the agent side resource manager class and configuration was inconsistent in the code and was inconsistently used in documentation and publication.  This commit cleans up that confusion by moving to `RM - Resource Manager`.  Some other smaller inconsistencies on the launch method class naming has been fixed as well.  Only one test needed fixing, the commit does not introduce any semantic changes.

### CODE REVIEW

**Comment by AymenFJA** [comment]
This make so much sense for me now. Thanks, @andre-merzky I will start working on the testing part as well.

**Comment by andre-merzky** [comment]
@AymenFJA : ping for review completion - thanks

**Comment by AymenFJA** [comment]
Sorry for the delays.

**Comment by andre-merzky** [comment]
Thanks @AymenFJA !

**Pull request merged**
