### PR TITLE
Minor changes from devel-mark

### PR DESCRIPTION
**Pull request by marksantcroos**
Hmmm, additional commits to the branch automagically gets added to the PR.

### CODE REVIEW

**Comment by andre-merzky** [comment]
We are mixing job submission and file system endpoint schemas -- but I don't have a better proposal which would not increase complexity.  Lets change that when it becomes a problem...

**Comment by andre-merzky** [comment]
Thanks!

**Comment by marksantcroos** [comment]
> We are mixing job submission and file system endpoint schemas

Isnt that a feature instead of a problem?

**Comment by andre-merzky** [comment]
Yes, maybe -- until I want to add gsissh & go, then it will become confusing... gsigo? ;)

**Comment by marksantcroos** [comment]
I would probably suggest `gogogadgetsftp`, but otherwise I agree.

The ultimate solution once this becomes a problem is probably "simple", exposing them separately.
Which is only a small change in the resource config and in most cases people will stick with the defaults anyway.

**Comment by andre-merzky** [comment]
Agree - we can do that once it's worthwhile to do so...

**Pull request merged**
