### PR TITLE
Disable ntp for now.

### PR DESCRIPTION
**Pull request by marksantcroos**
The timeout on ntplib.NTPClient().request() is only for the socket call, not for the name lookup.
In practice this comes down to 40 seconds per Profiler() instantiation when there is no outbound network connectivity.

You do the math ...

On the Crays the time of the systems seem to be in sync.

### CODE REVIEW

**Comment by marksantcroos** [comment]
I think the state of that NTP library is very dubious. For one thing, it doesnt even work on my laptop.

**Comment by andre-merzky** [comment]
What happens on your laptop?  I actually tested MacOS for once, it worked back then, and still does:

```
(ve)cameo:~ merzky$ uname -a
Darwin cameo.fritz.box 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

(ve)cameo:~ merzky$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ntplib
>>> from time import ctime
>>> c = ntplib.NTPClient()
>>> response = c.request('pool.ntp.org')
>>> print ctime(response.tx_time)
Wed Sep 23 19:47:14 2015
```

I am hesitant to just remove / disable it unconditionally.  It was added to solve a real problem, that of event ordering on combined profiles.  Otherwise I see negative durations on stampede, for example, which kind of screw with the whole analysis.

Let me look into ntplib timeouts.  I don't mind falling back to system time for nodes which can't use it, obviously...

**Comment by marksantcroos** [comment]
This is on my laptop.

```
$ python
Python 2.7.10 (default, Sep 22 2015, 10:25:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ntplib
>>> from time import ctime
>>> c = ntplib.NTPClient()
>>> response = c.request('pool.ntp.org')
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/ntplib.py", line 316, in request
    raise NTPException("No response received from %s." % host)
ntplib.NTPException: No response received from pool.ntp.org.

>>> 
```

Using ntpdate works fine, so its not a networking issue.
```
$ ntpdate -q pool.ntp.org
server 83.98.201.134, stratum 2, offset 0.012140, delay 0.03311
server 188.166.42.87, stratum 3, offset -0.000524, delay 0.05829
server 91.148.192.49, stratum 2, offset 0.012354, delay 0.03331
server 195.191.112.251, stratum 16, offset -0.033335, delay 0.09229
23 Sep 20:49:10 ntpdate[9577]: adjust time server 83.98.201.134 offset 0.012140 sec
```

**Comment by marksantcroos** [comment]
I agree that we need some synchronisation.

NTP is not a general viable option, and I would prefer to have one solution that works everywhere.

Wouldn't it be relatively easy to do some kind of broadcast over zmq and create an offset from that?

**Comment by andre-merzky** [comment]
synching times is a hard problem -- NTP is made to do it.  I would only look for other solutions where NTP does not work due to connectivity.  The main problem we are trying to solve is syncing between RP module and RP agent, and between different agents.  Compute nodes are likely not far off from head node clocks (although I have seen that actually happen to cause event reordering).

Using ZMQ would mean we implement our own, ntp like protocol, because you need to remove the communication delays from the equation.  rtt/2 may or may not be good enough.  Also, that works only within the agent at the moment, so cannot be an universal solution (yet).

I do have a solution to avoid the loopkup timeouts without changing much - I am testing that right now on BW.  That might not be an ultimate solution, but should take the urgency out of the discussion, I hope...

**Comment by andre-merzky** [comment]
Hey Mark, 

as discussed, here is the temporary workaround to avoid the accumulating dns lookup delays.  The ntp request delays are now limited to 1sec/call, which still adds up to several seconds per agent, depending on number of components.

The time source (`ntp` or `sys`) is now recorded in the initial profile timestamp, to make it simpler to revert ntp after data collection, if we so want.

I tested local and stampede, we probably should make sure that this does not trip anything  strange on BW.

**Comment by marksantcroos** [comment]
Looks good. Didnt actually run it (yet), as there are too many individual branches that I need.

**Pull request merged**
