### PR TITLE
fix agent argument handling for empty parameters

### PR DESCRIPTION
**Pull request by andre-merzky**
very simple fix for a problem which got triggered by some swift integration test.

### CODE REVIEW

**Comment by marksantcroos** [comment]
Whats the condition, `for arg in [None]:`?

**Comment by andre-merzky** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/fix/agent-argument-handling-2/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3995 makes sure that args is not `None`.  The added check should work ok for `args=[None]` -- that would be ignored, and an empty arg list would be returned, which later results in an empty arg string (`''`).

**Comment by andre-merzky** [comment]
FWIW, there is no check if `args` is a list -- that should be caught by the attrib interface on the CU description on the submission side...

**Comment by marksantcroos** [comment]
That was my question, how does the [None] end up there? User specified?

**Comment by andre-merzky** [comment]
Yes, user specified -- actually as `['-cf', '', '-par', '', ...]` -- the `arg[0]` stumbled over that...

**Comment by marksantcroos** [comment]
That doesn't necessarily give the results that the user expects then, does it?

**Comment by marksantcroos** [comment]
But also not sure what was intended.

**Comment by andre-merzky** [comment]
The former popen spawner handled it the same way: https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L3525

 We probably should add some documentation, but the policy really is: 'handle arguments as strings, if the arg value starts and ends with single quote, then pass it in single quote, otherwise pass it in double quotes.  So:

`args = ['a', '"b"', "c", "'d'", '', ""] ->  "a" "b" "c" 'd' '' ''`

**Comment by marksantcroos** [comment]
I mean, is there any use for "empty" arguments, and if not, shouldnt we warn and/or fail early?

**Comment by andre-merzky** [comment]
That actually changes what the executable sees as positional parameters.  If that is good practice is a different question, but I don't want to judge user code on that level.  It is technically legal to specify empty parameters:

```
$ echo test | cut -f 1 -d '' | grep ''
test
```

**Comment by marksantcroos** [comment]
Right, but I do we maintain that positionality now?

**Comment by andre-merzky** [comment]
yes -- an empty arg ends up as `''` on the command line.

**Comment by marksantcroos** [comment]
Ok, cool.

**Pull request merged**
