### PR TITLE
case insensitive verbose setting

### LINKED ISSUE #1208: Consistency in env variable values
RADICAL_PILOT_VERBOSE accepts both info and INFO. RADICAL_PILOT_AGENT_VERBOSE however accepts only INFO (fails with info).

Not critical, but I guess a easy fix.

### PR DESCRIPTION
**Pull request by andre-merzky**
This fixes #1208

### CODE REVIEW

**Comment by marksantcroos** [comment]
test this please

**Comment by andre-merzky** [comment]
Hmm, I did, and did again - I don't see it failing on lowercase settings of `RADICAL_PILOT_AGENT_VERBOSE`.  Do you?

**Comment by marksantcroos** [comment]
Haha, that was me using the instruction Manuel provided to trigger Jenkins rebuild, but I don't think it works.

@itomaldonado Btw, this acknowledges my earlier feeling that it would be better to use a "command" than some piece of natural language.

**Comment by andre-merzky** [comment]
Oops :D

**Pull request merged**
