### PR TITLE
fix rcfg expansion

### LINKED ISSUE #1887: Do not hardcode project number in resource_ornl.json

### PR DESCRIPTION
**Pull request by andre-merzky**
fixes #1887 .  Tests need to be added.

### CODE REVIEW

**Comment by mturilli** [comment]
We are still missing the automatic travis test. Any idea about why?

**Comment by andre-merzky** [comment]
@iparask : any idea why travis is not showing up?

**Comment by iparask** [comment]
None what so ever. Let me see how this can be fixed.

**Comment by andre-merzky** [comment]
@iparask : ping?

**Pull request merged**
