### PR TITLE
Also create separate info entries for Canceled and Failed units.

### PR DESCRIPTION
**Pull request by marksantcroos**
This addresses #801.

### CODE REVIEW

**Comment by marksantcroos** [comment]
Andre, feedback would be welcome whether this is the right approach or not.

**Comment by andre-merzky** [comment]
Your code works and yields the expected result AFAICS -- but I am not sure you would need it.  Wouldn't selecting all columns with a specific info entry and FAILED or CANCELED state yield the same result?  Because, changing the info entry now makes it more cumbersome for search for that info entry for failed and non-failed units.  But I may be missing something...

**Comment by marksantcroos** [comment]
> But I may be missing something...

If this refers to missing the original problem, then yes.

**Comment by andre-merzky** [comment]
Yes, I did miss that of course :(

**Comment by andre-merzky** [comment]
Yes, in this context this is the right thing to do I think.  Sorry again...

**Pull request merged**
