### PR TITLE
Update Amarel Resource Config

### PR DESCRIPTION
**Pull request by AymenFJA**
updating `Amarel` resource config

### CODE REVIEW

**Review by mtitov — APPROVED** [review]
LGTM! can you please make a test run for RP and feel free to merge! Thank you!

**Comment by AymenFJA** [comment]
> LGTM! can you please make a test run for RP and feel free to merge! Thank you!

@mtitov the test run is failing (`rp.session.hal0271.amarel.rutgers.edu.afa64.019499.0003.log`) with: 
```
1684787757.212 : rp.session.hal0271.amarel.rutgers.edu.afa64.019499.0003 : 38020 : 140123217000256 : DEBUG    : tar result:
---
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

---
2
1684787757.444 : rp.session.hal0271.amarel.rutgers.edu.afa64.019499.0003 : 38020 : 140123217000256 : ERROR    : failed to fetch pilot.0000 for profiles
Traceback (most recent call last):
  File "/cache/home/afa64/ve/rct/lib/python3.9/site-packages/radical/pilot/utils/session.py", line 215, in fetch_filetype
    raise RuntimeError('could not create tarball: %s' %
RuntimeError: could not create tarball: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

same error in `radical.saga.pty.log`: 
```
1684787756.515 : radical.saga.pty     : 38020 : 140123217000256 : DEBUG    : read : [    4] [  501] (\nSTATE : FAILED\n\nECODE=2\nSTART  : 1684787756\nSTOP   : 1684787756\n\nSTART_STDERR\ntar (child): bzip2: Cannot exec: No such file or directory\ntar (child): Error is not recoverable: exiting now\ntar: Child returned status 2\ntar: Error is not recoverable: exiting now\nEND_STDERR\n\nSTART_STDOUT\ntar (child): bzip2: Cannot exec: No such file or directory\ntar (child): Error is not recoverable: exiting now\ntar: Child returned status 2\ntar: Error is not recoverable: exiting now\nEND_STDOUT\n\n)
```

`radical-stack`: 
```
(rct) [afa64@hal0271 rp.session.hal0271.amarel.rutgers.edu.afa64.019499.0003]$ radical-stack

  python               : /cache/home/afa64/ve/rct/bin/python3
  pythonpath           :
  version              : 3.9.5
  virtualenv           : /cache/home/afa64/ve/rct

  radical.entk         : 1.30.0
  radical.gtod         : 1.20.1
  radical.pilot        : 1.34.0-v1.33.0-625-gbf3a4e2@update-amarel_config
  radical.saga         : 1.33.0
  radical.utils        : 1.33.0

```

**Comment by mtitov** [comment]
@AymenFJA can you please run without removing original line but adding a new one
```
"module load py-data-science-stack/5.1.0-kp807",
"module load python/3.9.6-gc563",
```

**Comment by AymenFJA** [comment]
> @AymenFJA can you please run without removing original line but adding a new one
> 
> ```
> "module load py-data-science-stack/5.1.0-kp807",
> "module load python/3.9.6-gc563",
> ```

@mtitov same issue with your suggestions.

**Comment by mtitov** [comment]
Just to keep track of the next actions - need to confirm that with the default settings for the `Session.close()` method (no need to set `download=True`) it is not an issue.

**Comment by AymenFJA** [comment]
@andre-merzky  @mtitov  [env.txt](https://github.com/radical-cybertools/radical.pilot/files/11619307/env.txt)

**Pull request merged**
