### PR TITLE
Fix/pip unalias

### PR DESCRIPTION
**Pull request by andre-merzky**
also removes an unneccessary 'unset' and fixes some doc strings.  

Tests: http://ci.radical-project.org/job/radical.pilot.devel/branch/hotfix%2F587/

### CODE REVIEW

**Comment by marksantcroos** [comment]
Does the test actually remove the existing ve? Otherwise its of little value.

**Comment by andre-merzky** [comment]
Each branch has its own workspace and ve, so yes, that is a new ve.

**Comment by marksantcroos** [comment]
Obviously I'm talking about the remote ve.

**Comment by marksantcroos** [comment]
And can we get rid of the code duplication in the process or you dont feel comfortable doing that now?

**Comment by andre-merzky** [comment]
Ah, sorry, got it...  Well, pip is also used in the update mode, and when the radical stack is installed.  That holds at least for some of the target resources (like, local).  For the others the tests show at least that the branch still works with the current configs...

code duplication: that is the 'rehash' on pip which is done in several places?  We could do that in a method, sure...

**Comment by marksantcroos** [comment]
Thanks for the de-dup.
While reviewing, I found that virtenv_activate is always called with an argument, but that doesnt seem to be used?

**Comment by marksantcroos** [comment]
Passes visual inspection and tests.

**Pull request merged**
