### PR TITLE
Update launch method `aprun`

### PR DESCRIPTION
**Pull request by mtitov**

### CODE REVIEW

**Comment by mtitov** [comment]
> This version now ignores the scheduler defined slots.

right, Theta doesn't like it (it is possible to use the current implementation of `aprun`, but only without option `-L`)

> Should we add a code path where slots are used again?

yeah, I keep the corresponding code commented out and did extend it with possibility to share nodes (option `-F`)
https://github.com/radical-cybertools/radical.pilot/blob/726762222fdee76daa98d07286a64ef670c44ad4/src/radical/pilot/agent/launch_method/aprun.py#L115-L119

**Review by andre-merzky — APPROVED** [review]
Fair - since we don't have other `aprun` machines at the moment, that makes sense.  We can revisit in case other machines appear...

**Comment by andre-merzky** [comment]
@mtitov : can this be merged?

**Comment by mtitov** [comment]
Andre, it is, thank you for remind!

**Pull request merged**
