### PR TITLE
Hotfix/deployment

### PR DESCRIPTION
**Pull request by andre-merzky**
This PR removes code which handles sdist staging and installation into the agent space.  Instead we rely on reusing the client side VE or install RP and dependencies via pip.

### CODE REVIEW

**Comment by andre-merzky** [comment]
Our rules don's seem to run tests when PR points to master, thus pointing to devel for now.

**Comment by andre-merzky** [comment]
@mtitov , @mturilli : this is ready for review now.  The PR is a bit rough, a proper cleanup would need additional changes in RU.  I'll leave that for the next sprint, this PR is just to get things going again.

**Review by mturilli — APPROVED** [review]
Looks good to me. We can merge after Mikhail tests it on Frontier.

**Review by mtitov — APPROVED** [review]
LGTM!

**Comment by andre-merzky** [comment]
> Looks good to me. We can merge after Mikhail tests it on Frontier.

I tested on Frontier by now - merging.

**Pull request merged**
