### PR TITLE
improve static ve creation script

### PR DESCRIPTION
**Pull request by andre-merzky**
This improves the RP script for creating a static resource VE.  

Srinivas, can you please give this a try in the context of #1546?  Basically, please purge the VE in `radical.pilot.sandbox` on BW, and create a new one with

```
radicalpilot-create-static-ve ve.bw
``` 

The exact name of the VE may vary, depending on the RP version you used.  After that VE got creeated, please run your application again, to check if the resulting VE is viable.

On bw, you probably need to `module load bwpy` before running the script.

### CODE REVIEW

**Comment by SrinivasMushnoori** [comment]
Hi Andre, if I understand you correctly, I need to create a virtual environment on blue waters, install RP there from the appropriate branch, and use the ```radicalpilot-create-static-ve ve.bw``` command there, yes?

Doing so returns the following error:

```
(RP_Test)mushnoor@h2ologin2:~/scratch/virtualenv_install/virtualenv-1.9/radical.pilot> pip install .
/u/sciteam/mushnoor/RP_Test/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

If I have misunderstood you,  my apologies, could you clarify?

**Comment by andre-merzky** [comment]
Hey Srinivas, 

thanks for asking! :-)
You actually don't need to install RP for testing the script: at least in this specific PR, its really just that one script which has changed, so you can download it directly from the branch, with something like:

```
wget https://raw.githubusercontent.com/radical-cybertools/radical.pilot/feature/create_ve/bin/radicalpilot-create-static-ve
```

Having said that: BW really screwed up their python installation now, or so it seems.  It took me a while, but I think here is what should get you going:

```
$ module load bwpy
$ bwpy-environ -- python radicalpilot-create-static-ve ve.bw
```

This is documented [here](https://bluewaters.ncsa.illinois.edu/python).  As said earlier: the name of the VE you want to recreate may differe - but the result should be a static ve your Pilot hopefully can use.

I did not try the full test - let me please know when you get stuck again, ok?

**Comment by SrinivasMushnoori** [comment]
Hi Andre, thanks a bunch for the clarification. It's still failing:
```
mushnoor@h2ologin1:~/scratch/radical.pilot.sandbox> bwpy-environ -- python radicalpilot-create-static-ve ve.bw
  File "radicalpilot-create-static-ve", line 14
    help(){
          ^
SyntaxError: invalid syntax
```

**Comment by andre-merzky** [comment]
Well, this was an exceptionally stupid proposal from me, apologies!  The script is a shell script, not a python script, and that should have been:

```
$ module load bwpy
$ bwpy-environ -- /bin/sh radicalpilot-create-static-ve ve.bw
```

Alternatively you can try `/bin/bash` (but /bin/sh should work, so please let me know).

**Comment by SrinivasMushnoori** [comment]
It does seem to create a virtualenv, but the job still fails (possibly for a different reason). I'm exploring this right now and I'll update you as soon as I find something, does that sound okay?

**Comment by SrinivasMushnoori** [comment]
Hi Andre, update: it still fails. Although the VE is created, RP seems to be unable to use it. Bootstrap_1.out is attached, as are the logfiles. Please let me know if you need more input from me.


[rp_session.gz](https://github.com/radical-cybertools/radical.pilot/files/1691860/rp_session.gz)
[bootstrap_1.zip](https://github.com/radical-cybertools/radical.pilot/files/1691861/bootstrap_1.zip)

**Comment by andre-merzky** [comment]
The script now understands an additional parameter - when that is given as `bw`, then the script will perform the required VE patching on its own.

This is likely to break with the next BW module update.

**Pull request closed without merging**
