### PR TITLE
fixed directory to be staged (staging tutorial)

### PR DESCRIPTION
**Pull request by mtitov**

### CODE REVIEW

**Comment by mtitov** [comment]
@mturilli staging tutorial passed!!

**Comment by mturilli** [comment]
Should we add to the tutorial a discussion of relative vs. absolute paths?

**Review by mturilli — APPROVED** [review]
LGTM. See comment before merging

**Comment by mtitov** [comment]
> Should we add to the tutorial a discussion of relative vs. absolute paths?

@mturilli I've added it

**Review by mturilli — APPROVED** [review]
LGTM

**Pull request merged**
