### PR TITLE
doc update

### LINKED ISSUE #1242: Create databases 'on the fly'
We have a requirement from one of our collaborators to be able to create databases 'on the fly' given the URL to an existing mongodb instance. See https://github.com/radical-collaboration/GB-SC18/issues/2.

I was checking if this was already supported in RP by doing the following:

```
session = rp.Session(database_url='mongodb://rp:rp@ds015335.mlab.com:15335/', database_name = 'test_newdb')
```
but this fails with:
```
radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'mongodb://rp:rp@ds015335.mlab.com:15335/test_newdb' incorrect?): command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('autoAuthorize', 1), ('payload', Binary('n,,n=rp,r=ODg3NjU3Nzg4NjI0', 0))]) on namespace test_newdb.$cmd failed: Authentication failed
```

It might be that it is supported but I'm specifying the parameters incorrectly, do let me know in this case.

But if this feature is not supported, I suppose something like the following should suffice(?):

```
from pymongo import Connection
connection = Connection('mongodb://rp:rp@ds015335.mlab.com','15335')
db = connection['test_newdb']
```

Although this can be done in entk and passed to RP, I think the appropriate place to do this might be RP itself. Thoughts?

### PR DESCRIPTION
**Pull request by andre-merzky**
fixes #1242

### CODE REVIEW

**Comment by vivek-bala** [comment]
Hey @andre-merzky , would you be ok with "RP will not create that DB on the fly and requires the DB to be setup prior to creating the session object. But RP will create collections in that DB on its own, named after RP session IDs" ?

**Comment by andre-merzky** [comment]
Absolutely!  Would you be so kind to update this PR?  Thanks!

**Comment by vivek-bala** [comment]
Done!

**Comment by andre-merzky** [comment]
Thanks!

**Pull request merged**
