### PR TITLE
Feature/remote orte

### PR DESCRIPTION
**Pull request by andre-merzky**
This pull request covers a number of configuration and bootstrap changes, which are preparatory for te planned agent splitup.

### CODE REVIEW

**Comment by marksantcroos** [comment]
I think we concluded we could kill this branch and PR, right?

**Comment by andre-merzky** [comment]
Let me check if anything is missing in split_agent -- but I think not.

**Comment by andre-merzky** [comment]
yeah, I think its ok to remove it, and to do the PR from split_agent to devel...

**Comment by marksantcroos** [comment]
Ack. I don't think I have objection against doing that (now).

**Pull request closed without merging**
