### PR TITLE
fix GPU maps

### PR DESCRIPTION
**Pull request by andre-merzky**
This fixes two small errors related to `CUDA_VISIBLE_DEVICE` settings (slot dict was incorrectly accessed) and gpu mapping in the hombre scheduler (slot dict was incorrectly created).

### CODE REVIEW

**Comment by iparask** [comment]
Did you branch out of the `feature/gpu_devices` branch or `devel`? It seems like the former, more than the later.

**Comment by andre-merzky** [comment]
@iparask : this PR is by now fairly small and contained - it basically just moves code around and fixes the affected parts in the hombre scheduler.  Can you please give it another checkup, so that we can close this out?  Thanks!

**Comment by iparask** [comment]
I assume flake8 and pylint passes, right?

**Comment by andre-merzky** [comment]
Pylint is not yet there, I'll have to address this in a separate commit - apologies...

**Pull request merged**
