### PR TITLE
This optimization breaks for tagged units - remove.

### PR DESCRIPTION
**Pull request by andre-merzky**
@iparask : please make sure this does the trick.  Thanks!

### CODE REVIEW

**Comment by iparask** [comment]
As soon as, I run a test I will let you know! Thank you @andre-merzky

**Comment by andre-merzky** [comment]
Can you please check why the update worker did not come up?

**Comment by iparask** [comment]
I think it was a system issue. The second test started but the first unit did not get scheduled. The last state was `AGENT_SCHEDULING_PENDING`.

**Comment by andre-merzky** [comment]
Sorry Ioannis, the information from the last message is not enough to understand whats up.  Do you have a  set if CUDs and PDs to reproduce this?

**Comment by iparask** [comment]
The Pilot description had  64 cores and 4 GPUs it was submitted at the GPU queue of Bridges. This stopped at the very first unit which is a single core unit that was submitted alone.

**Comment by andre-merzky** [comment]
Can you attach the logs?  This sounds unrelated to this PR, really, doesn't it?  Any errors in the agent logs?

**Comment by andre-merzky** [comment]
Thanks

**Pull request merged**
