### PR TITLE
Release/0.35

### PR DESCRIPTION
**Pull request by andre-merzky**

### CODE REVIEW

**Comment by shantenujha** [comment]
http://radicalpilot.readthedocs.org/en/latest/ still points to 0.33

Can we automate so that documentation points to latest version?

**Comment by andre-merzky** [comment]
Thanks for the reminder - the doc update has been pushed.

**Comment by andre-merzky** [comment]
Mark -- our release procedure is silent about the fate of the release branches after release.  I would suggest we delete them, as I don't think we need more than the tags to base eventual hotfixes on a release?

**Comment by marksantcroos** [comment]
Tags are enough, branches can go.

**Pull request merged**
