### PR TITLE
ensure correct env for raptor

### PR DESCRIPTION
**Pull request by andre-merzky**
@AymenFJA : please apply this PR as well.

### CODE REVIEW

**Comment by AymenFJA** [comment]
@andre-merzky  The `hotfix/raptor_env` is missing the `TASK_MODE ` under `task_description` and `__init__`. Was this branched out from `master`?

**Comment by andre-merzky** [comment]
> @andre-merzky The `hotfix/raptor_env` is missing the `TASK_MODE ` under `task_description` and `__init__`. Was this branched out from `master`?

Yes - please merge it into your working branch to test.

**Comment by AymenFJA** [comment]
@andre-merzky , Sorry for that, after merging both branches locally: I am getting this error:
```python
1643914294.304 : agent_executing.0000 : 8104  : 139792079337216 : DEBUG    : Launching task with MPIEXEC
1643914294.305 : agent_executing.0000 : 8104  : 139792079337216 : DEBUG    : mpiexec cmd: /usr/bin/mpiexec -host localhost -n 1   $RP_TASK_SANDBOX/master.000000.exec.sh
1643914294.306 : agent_executing.0000 : 8104  : 139792079337216 : ERROR    : error running Task
Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/executing/popen.py", line 121, in work
    self._handle_task(task)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/executing/popen.py", line 326, in _handle_task
    tmp += self._get_task_env(task, launcher)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/executing/popen.py", line 690, in _get_task_env
    ret += '. %s\n' % launcher.get_task_named_env(td['named_env'])
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/launch_method/base.py", line 202, in get_task_named_env
    ru.env_prep(environment=ru.env_read(src),
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/rp_install/lib/python3.8/site-packages/radical/utils/env.py", line 52, in env_read
    with ru_open(fname, 'r') as fin:
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/rp_install/lib/python3.8/site-packages/radical/utils/misc.py", line 951, in ru_open
    return open(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/aymen/radical.pilot.sandbox/rp.session.js-17-213.jetstream-cloud.org.aymen.019026.0018/pilot.0000/env/rp_named_env.ve_raptor.env'
```

Although the file does exist under `pilot.0000/env/` which is a symlink : 

```shell
drwxrwx---   2 aymen aymen  4096 Feb  3 13:23 .
drwxrwx--- 168 aymen aymen 20480 Feb  3 13:26 ..
-rw-rw----   1 aymen aymen  4476 Feb  3 12:51 bs0_active.env
-rw-rw----   1 aymen aymen  3418 Feb  3 12:50 bs0_orig.env
-rw-rw----   1 aymen aymen  4144 Feb  3 12:51 bs0_orig.sh
-rw-rw----   1 aymen aymen  3479 Feb  3 12:50 bs0_pre_0.env
-rw-rw----   1 aymen aymen  4160 Feb  3 12:51 bs0_pre_0.sh
-rw-rw----   1 aymen aymen  5027 Feb  3 12:51 lm_fork.sh
-rw-------   1 aymen aymen  3886 Feb  3 12:51 lm_fork.shu_5_62bs
-rw-rw----   1 aymen aymen  5027 Feb  3 12:51 lm_mpiexec.sh
-rw-------   1 aymen aymen  3886 Feb  3 12:51 lm_mpiexec.shnmdv4t4i
-rw-------   1 aymen aymen  3886 Feb  3 12:51 lm_mpiexec.shy1u751ma
-rw-rw----   1 aymen aymen  5027 Feb  3 12:51 lm_mpirun.sh
lrwxrwxrwx   1 aymen aymen    43 Feb  3 12:51 rp_named_env.ve_raptor -> /home/aymen/radical.pilot.sandbox/ve_raptor
lrwxrwxrwx   1 aymen aymen    47 Feb  3 12:51 rp_named_env.ve_raptor.env -> /home/aymen/radical.pilot.sandbox/ve_raptor.env
-rw-rw----   1 aymen aymen    61 Feb  3 12:51 rp_named_env.ve_raptor.sh
```
But the real file which the link is pointing to does not exist: `/home/aymen/radical.pilot.sandbox/ve_raptor.env`

I have attached the pilot sandbox below:
[pilot.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/7997586/pilot.0000.zip)

**Comment by andre-merzky** [comment]
@AymenFJA - sorry, I missed your reply!

Can you please give me the stack with which you ran the above?

**Comment by AymenFJA** [comment]
@andre-merzky 

```

  python               : /home/aymen/ve/raptor/bin/python3
  pythonpath           :
  version              : 3.7.6
  virtualenv           : /home/aymen/ve/raptor

  radical.gtod         : 1.6.7
  radical.pilot        : 1.11.2-v1.11.2-80-gb3a1313@feature-parsl_raptor_executor
  radical.saga         : 1.11.1
  radical.utils        : 1.11.0-v1.11.0-1-g7c9997f@hotfix-env_write

```
`feature-parsl_raptor_executor` is a branch our from `raptor_workers`. I have merged the `[hotfix/raptor_env]` with it locally.

**Comment by AymenFJA** [comment]
> ```shell
> 'redis_link'
> ```
@andre-merzky Sorry for that it is designed for Colmena, you can just add `pd.redis_link = ' '` where `pd` is the pilot description object.

```python
        pd = rp.PilotDescription(cfg.pilot_descr)
        pd.cores   = n_masters * (cpn / masters_pn)
        pd.gpus    = 0
        pd.redis_link = ''
```

**Comment by mtitov** [comment]
@AymenFJA can you please find in logs the following lines and bring them here
https://github.com/radical-cybertools/radical.pilot/blob/devel/bin/radical-pilot-create-static-ve#L192-L204

**Comment by AymenFJA** [comment]
@mtitov, I could not find them in the logs, I think the bootstrapper couldn't reach these lines.

**Pull request merged**
