### PR TITLE
fix botched cherry-pick

### LINKED ISSUE #1043: CU env is not correct
I am trying to execute a small script on Stampede that requires two extra modules. The error I got from the CU execution indicated that the environment was empty of any module, despite the fact that I was loading everything that was needed.

Based on Andre's suggestion I executed the following

```
cudesc.pre_exec = ['set -x;env;module load netcdf pnetcdf;env;set +x']
cudesc..executable = 'env'
```

Here is the output of the first env

```
MANPATH=:/usr/share/man
SHELL=/bin/bash
SSH_CLIENT=129.114.90.167 51926 22
MIC_I_MPI_OFA_ADAPTER_NAME=mlx4_0
LMOD_PKG=/opt/apps/lmod/lmod
OLDPWD=/home1/03170/tg824689
QTDIR=/usr/lib64/qt-3.3
RP_SESSION_ID=rp.session.iparask-VirtualBox.iparask.016973.0013
QTINC=/usr/lib64/qt-3.3/include
LMOD_VERSION=6.0.24
LC_ALL=en_US.UTF-8
RP_UNIT_ID=unit.000005
USER=tg824689
ARMCI_OPENIB_DEVICE=mlx4_0
RP_PILOT_ID=pilot.0000
__PERSONAL_PATH__=1
LMOD_PREPEND_BLOCK=normal
ARCHIVER=
PATH=/scratch/03170/tg824689/anaconda2/bin:/home1/03170/tg824689/bin:/scratch/03170/tg824689/java/jdk1.8.0_65/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/ofed/bin:/opt/ofed/sbin
MAIL=/var/mail/tg824689
I_MPI_OFA_ADAPTER_NAME=mlx4_0
STOCKYARD=/work/03170/tg824689
WORK=/work/03170/tg824689
LMOD_SETTARG_CMD=:
RP_SPAWNER_ID=agent_0.AgentExecutingComponent.0.child
PWD=/work/03170/tg824689/radical.pilot.sandbox/rp.session.iparask-VirtualBox.iparask.016973.0013-pilot.0000/unit.000005
I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
LANG=en_US.UTF-8
MODULEPATH=/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
LMOD_CMD=:
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
ENVIRONMENT=BATCH
HOME=/home1/03170/tg824689
SHLVL=2
BASH_ENV=/etc/tacc/tacc_functions
LOGNAME=tg824689
MV2_IBA_HCA=mlx4_0
RP_AGENT_ID=agent_0
CVS_RSH=ssh
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=129.114.90.167 51926 129.114.90.167 22
MODULESHOME=/opt/apps/lmod/lmod
LESSOPEN=||/usr/bin/lesspipe.sh %s
LMOD_FULL_SETTARG_SUPPORT=no
ARCHIVE=
LMOD_DIR=/opt/apps/lmod/lmod/libexec
G_BROKEN_FILENAMES=1
LMOD_COLORIZE=yes
SCRATCH=/scratch/03170/tg824689
MIC_I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
BASH_FUNC_module%%=() {  eval $($LMOD_CMD bash "$@");
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
}
_=/bin/env
```

The output of the second env

```
MANPATH=:/usr/share/man
SHELL=/bin/bash
SSH_CLIENT=129.114.90.167 51926 22
MIC_I_MPI_OFA_ADAPTER_NAME=mlx4_0
LMOD_PKG=/opt/apps/lmod/lmod
OLDPWD=/home1/03170/tg824689
QTDIR=/usr/lib64/qt-3.3
RP_SESSION_ID=rp.session.iparask-VirtualBox.iparask.016973.0013
QTINC=/usr/lib64/qt-3.3/include
LMOD_VERSION=6.0.24
LC_ALL=en_US.UTF-8
RP_UNIT_ID=unit.000005
USER=tg824689
ARMCI_OPENIB_DEVICE=mlx4_0
RP_PILOT_ID=pilot.0000
__PERSONAL_PATH__=1
LMOD_PREPEND_BLOCK=normal
ARCHIVER=
PATH=/scratch/03170/tg824689/anaconda2/bin:/home1/03170/tg824689/bin:/scratch/03170/tg824689/java/jdk1.8.0_65/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/ofed/bin:/opt/ofed/sbin
MAIL=/var/mail/tg824689
I_MPI_OFA_ADAPTER_NAME=mlx4_0
STOCKYARD=/work/03170/tg824689
WORK=/work/03170/tg824689
LMOD_SETTARG_CMD=:
RP_SPAWNER_ID=agent_0.AgentExecutingComponent.0.child
PWD=/work/03170/tg824689/radical.pilot.sandbox/rp.session.iparask-VirtualBox.iparask.016973.0013-pilot.0000/unit.000005
I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
LANG=en_US.UTF-8
MODULEPATH=/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
LMOD_CMD=:
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
ENVIRONMENT=BATCH
HOME=/home1/03170/tg824689
SHLVL=2
BASH_ENV=/etc/tacc/tacc_functions
LOGNAME=tg824689
MV2_IBA_HCA=mlx4_0
RP_AGENT_ID=agent_0
CVS_RSH=ssh
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=129.114.90.167 51926 129.114.90.167 22
MODULESHOME=/opt/apps/lmod/lmod
LESSOPEN=||/usr/bin/lesspipe.sh %s
LMOD_FULL_SETTARG_SUPPORT=no
ARCHIVE=
LMOD_DIR=/opt/apps/lmod/lmod/libexec
G_BROKEN_FILENAMES=1
LMOD_COLORIZE=yes
SCRATCH=/scratch/03170/tg824689
MIC_I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
BASH_FUNC_module%%=() {  eval $($LMOD_CMD bash "$@");
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
}
_=/bin/env
```

The output of the third env

```
MANPATH=:/usr/share/man
SHELL=/bin/bash
SSH_CLIENT=129.114.90.167 51926 22
MIC_I_MPI_OFA_ADAPTER_NAME=mlx4_0
LMOD_PKG=/opt/apps/lmod/lmod
OLDPWD=/home1/03170/tg824689
QTDIR=/usr/lib64/qt-3.3
RP_SESSION_ID=rp.session.iparask-VirtualBox.iparask.016973.0013
QTINC=/usr/lib64/qt-3.3/include
LMOD_VERSION=6.0.24
LC_ALL=en_US.UTF-8
RP_UNIT_ID=unit.000005
USER=tg824689
ARMCI_OPENIB_DEVICE=mlx4_0
RP_PILOT_ID=pilot.0000
__PERSONAL_PATH__=1
LMOD_PREPEND_BLOCK=normal
ARCHIVER=
PATH=/scratch/03170/tg824689/anaconda2/bin:/home1/03170/tg824689/bin:/scratch/03170/tg824689/java/jdk1.8.0_65/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/ofed/bin:/opt/ofed/sbin
MAIL=/var/mail/tg824689
I_MPI_OFA_ADAPTER_NAME=mlx4_0
STOCKYARD=/work/03170/tg824689
WORK=/work/03170/tg824689
LMOD_SETTARG_CMD=:
RP_SPAWNER_ID=agent_0.AgentExecutingComponent.0.child
PWD=/work/03170/tg824689/radical.pilot.sandbox/rp.session.iparask-VirtualBox.iparask.016973.0013-pilot.0000/unit.000005
I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
LANG=en_US.UTF-8
MODULEPATH=/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
LMOD_CMD=:
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
ENVIRONMENT=BATCH
HOME=/home1/03170/tg824689
SHLVL=2
BASH_ENV=/etc/tacc/tacc_functions
LOGNAME=tg824689
MV2_IBA_HCA=mlx4_0
RP_AGENT_ID=agent_0
CVS_RSH=ssh
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=129.114.90.167 51926 129.114.90.167 22
MODULESHOME=/opt/apps/lmod/lmod
LESSOPEN=||/usr/bin/lesspipe.sh %s
LMOD_FULL_SETTARG_SUPPORT=no
ARCHIVE=
LMOD_DIR=/opt/apps/lmod/lmod/libexec
G_BROKEN_FILENAMES=1
LMOD_COLORIZE=yes
SCRATCH=/scratch/03170/tg824689
MIC_I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
BASH_FUNC_module%%=() {  eval $($LMOD_CMD bash "$@");
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
}
_=/bin/env
```

### PR DESCRIPTION
**Pull request by andre-merzky**
(re)fixes #1043 and #1276.

### CODE REVIEW

**Comment by iparask** [comment]
Andre, when do you think this is going to be merged in devel?

**Comment by andre-merzky** [comment]
@ibethune @itomaldonado what is the merge policy when the jenkins tests fail?

**Comment by ibethune** [comment]
So IMO, since the Jenkins service is under development, we are no completely relying on it, so if @andre-merzky is happy that the failure is unrelated to changes in this branch, then we can merge.  I will create a new ticket for the failure that the tester picked up. (#1295)

**Comment by andre-merzky** [comment]
Lets do it for this one then indeed - I am confident, and @iparask is waiting...  Thanks!

**Pull request merged**
