### PR TITLE
Enable building of netifaces module on bw.

### PR DESCRIPTION
**Pull request by marksantcroos**
Not sure who is at fault here, but the fix is relatively robust.

### CODE REVIEW

**Comment by marksantcroos** [comment]
I've been able to repeat this multiple times with a clean VE.
Does it really not work for you?

**Comment by andre-merzky** [comment]
It really   did not.  But I am just now installing a new local ve, purge bashrc completely, remove sandbox root etc.  Lets see where this gets me...

**Comment by marksantcroos** [comment]
Ok, lets see who screwed up then :)

**Comment by andre-merzky** [comment]
someone else, I am sure :)

Problem is that if that works now for me, I'll not be able to tell why.  Which is not really comforting...  Lets see (queued)

**Comment by marksantcroos** [comment]
You can click this button now!
```
        ||
        ||
      \ || /
        \/
```

**Comment by andre-merzky** [comment]
I did, and then also this one

```
                                                                                    /\
                                                                                   /||\
                                                                                    ||
                                                                                    ||
```

**Comment by marksantcroos** [comment]
```
 -------------------------
< Boy, are we having fun! >
 ------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by andre-merzky** [comment]
Is this the 90'ies or what??

**Pull request merged**
