### PR TITLE
Add config `.json` file for FU Berlin allegro cluster

### PR DESCRIPTION
**Pull request by jhprinz**
This was tested from inside the IMP subdomain of the FU Berlin. The necessary mongodb server needs to reside within a subdomain accessible from the allegro cluster nodes. 

The cluster connects to nodes using `rsh` and not `ssh` and hence requires the still experimental rsh support in branch `lm_rsh` #1172 .

### CODE REVIEW

**Comment by jhprinz** [comment]
@andre-merzky pinging André for review. Thanks for all the help. It works robustly now.

**Comment by andre-merzky** [comment]
Thanks for the PR, JH! :)  We will need to merge #1172 before this one, but that should not take long either.

Best, Andre.

**Comment by marksantcroos** [comment]
They seem to overlap though. Is the only delta between this and #1172 the `fub_allegro.json`?

Note that the json file needs to be renamed to match the other files, e.g. `resource_fub.json`.

**Comment by andre-merzky** [comment]
The only diff after merging #1172 *should* be the allegro config - but I did not check.  Agree on the rename.

**Comment by andre-merzky** [comment]
JH, can you please merge from devel again, and do the config file rename to `resource_fub.json`?  Thanks!

**Comment by jhprinz** [comment]
sorry. I realized too late that I used your branch. Sure...

**Comment by jhprinz** [comment]
My fault... Closing and opening it again...

**Pull request closed without merging**
