### PR TITLE
re-order termination

### PR DESCRIPTION
**Pull request by andre-merzky**
`self.terminate` was set too early in the pilot manager, so that the `wait_pilots` call never actually waited for the pilots, but bailed out immediately complaining about timeout.  This PR fixes that - but also cleans up the state reporting done by the pilot, to re-introduce the `rp_state_push` utility to account for clean state pushes on bootstrap failures.

### CODE REVIEW

**Comment by mturilli** [comment]
Yes! 👍 👍 👍  We should probably get this out with the next release? :D

**Comment by andre-merzky** [comment]
Yes, absolutely.

**Comment by andre-merzky** [comment]
This fixes #2049 and radical-collaboration/Glatard-Lab/issues/1

**Comment by andre-merzky** [comment]
Thanks @iparask !

**Pull request merged**
